# Generated by Django 2.2.3 on 2019-07-31 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships_p1', '0002_auto_20190731_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=20)),
                ('time', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('wage', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='viewer',
            name='films',
            field=models.ManyToManyField(related_name='viewers', to='relationships_p1.Film'),
        ),
    ]
