# Generated by Django 2.2.3 on 2019-07-31 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships_p1', '0003_auto_20190731_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='workers',
            field=models.ManyToManyField(related_name='shifts', to='relationships_p1.Worker'),
        ),
    ]
